### ISSUE TITLE
srun Error

### ISSUE THREAD

**Issue by Ronchy2000** [silverling/srun-login#2]
问题日志：2024/06/20 11:36:36 Start
2024/06/20 11:36:36 Use given host: https://w.xidian.edu.cn/srun_portal_success?ac_id=8&theme=pro
2024/06/20 11:36:36 Offline, try to login
2024/06/20 11:36:36 Error: parse response failed
2024/06/20 11:36:36 Error: parse challenge failed, resp: map[]
2024/06/20 11:36:41 Quit

**Comment by Ronchy2000** [comment]
校园网每次息屏回来都要手动重连，改软件重连失败

**Comment by silverling** [comment]
你好，根据提供的日志，你的配置文件的 `host` 填写有误。`host` 的格式应该为 `http://domain`，例如 `http://w.xidian.edu.cn`

如果你是西电校园网用户，可以将配置文件 `config.yaml` 中的 `host` 所在行删除，这样程序会使用默认的 `http://10.255.44.33` 作为登入点。

**Comment by zstar1003** [comment]
LGTM

**Comment by Ronchy2000** [comment]
2024/06/20 20:42:38 Start
2024/06/20 20:42:38 Host is empty, use default host: http://10.255.44.33
2024/06/20 20:42:38 Offline, try to login
2024/06/20 20:42:38 Login failed, result: login_error
我邮箱你吧

**Comment by Ronchy2000** [comment]
我有尝试过抓取Request URL登录，奈何每次登录都是加密过的，对方使用了加密，以确保每个请求的唯一性，防止重放攻击，每次的校验和也在变化。意外中发现该repo，尝试后发现使用其仍然无法登录，希望进一步咨询~

**Comment by silverling** [comment]
可以看一下你的配置文件 `config.yaml` 的内容吗（学号和密码部分可以用星号代替）？

**Comment by silverling** [comment]
已更新 README 相关使用说明。

**Comment by zstar1003** [comment]
What can I say？！
